### ISSUE TITLE
Homekit doesn't work if you're not connected to the wifi

### ISSUE THREAD

**Issue by JorgeAnzola** [JorgeAnzola/home-assistant-config#49]

**Comment by martijnvanonz** [comment]
https://support.apple.com/nl-nl/guide/watch/apd1af68cb2a/watchos

**Comment by JorgeAnzola** [comment]
That makes sense, cause I removed the Apple TV 🤦

**Comment by JorgeAnzola** [comment]
Fixed when adding the Apple TV back
